name: NPM Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v2
        with:
          runtime: node@22
          cache: true

      - run: pnpm type-check
      - run: pnpm test
      - run: pnpm build

      - name: Publish
        run: pnpm publish --access public
